#!/usr/bin/env bash

set -euo pipefail

# Ensure environment is initialised.
test -n "$SMTP_HOST"
test -n "$SMTP_PORT"
test -n "$SMTP_USER"
test -n "$SMTP_TOKEN"
# test -n "$MARIADB_USER"
# test -n "$MARIADB_PASSWORD"
# test -n "$MARIADB_DATABASE"
test -n "$REGO_DB_CONNECT_STRING"

# Get directory of script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Rebuild docker image.
docker build -f "$DIR/Dockerfile" -t apsiminitiative/registration-site:latest "$DIR"

# Restart the container with the rebuild image, ignoring any errors while
# stopping the running container.
docker-compose -f "$DIR/docker-compose.yml" down || echo Ignoring errors...
docker-compose -f "$DIR/docker-compose.yml" up -d
