version: '3.1'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped

    volumes:
      - /data/jenkins:/var/jenkins_home
    networks:
      - apsim

networks:
  apsim:
    external: true
