#!/usr/bin/env bash

# This script will deploy the APSIM.Builds website using docker compose.
set -euo pipefail

# Rebuild docker image.
docker build --no-cache -t apsiminitiative/apsim-builds:latest .

# Restart all the containers
cd ..
./deploy.sh all


