#!/usr/bin/env bash
#
# This script will deploy the APSIM.Builds website using docker-compose.
set -euo pipefail

# Ensure the required environment variables are set.
test -n "$JENKINS_URL"
test -n "$JENKINS_TOKEN_NG"
test -n "$JWT_SECRET_KEY"
test -n "$HMAC_SECRET_KEY"
test -n "$DOCUMENTATION_PATH"
test -n "$NG_DB_CONNECTION_STRING"
test -n "$OLD_DB_CONNECTION_STRING"
test -n "$MARIADB_PASSWORD"

# Get directory of script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Rebuild docker image.
docker build -f "$DIR/Dockerfile" -t apsiminitiative/apsim-builds:latest "$DIR"

# Restart the container with the rebuilt image, ignoring any errors while
# stopping the running container.
docker-compose -f "$DIR/docker-compose.yml" down || echo Ignoring errors...
docker-compose -f "$DIR/docker-compose.yml" up -d
