#!/usr/bin/env bash
#
# This script will deploy the APSIM.Builds website using docker-compose.
set -euo pipefail

# Ensure the required environment variables are set.
test -n "$JWT_SECRET_KEY"
test -n "$HMAC_SECRET_KEY"
test -n "$DOCUMENTATION_PATH"
test -n "$INSTALLERS_PATH"
test -n "$NG_DB_CONNECTION_STRING"
test -n "$OLD_DB_CONNECTION_STRING"
test -n "$MARIADB_PASSWORD"
test -n "$GITHUB_PAT"

# Rebuild docker image.
docker build --no-cache -t apsiminitiative/apsim-builds:latest .

# Restart all the containers
cd ..
./deploy.sh all


