version: '3.1'

services:
  website:
    image: apsiminitiative/apsim-builds:latest
    container_name: apsim-builds
    restart: unless-stopped
    environment:
      - APACHE_LOG_DIR=/usr/local/apache2/logs
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_TOKEN_NG=${JENKINS_TOKEN_NG}
      - JENKINS_TOKEN_CLASSIC=${JENKINS_TOKEN_CLASSIC}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - HMAC_SECRET_KEY=${HMAC_SECRET_KEY}
      - DOCUMENTATION_PATH=/var/builds/docs
      - INSTALLERS_PATH=/var/builds/installers
      - NG_DB_CONNECTION_STRING=${NG_DB_CONNECTION_STRING}
      - OLD_DB_CONNECTION_STRING=${OLD_DB_CONNECTION_STRING}
      - GITHUB_PAT=${GITHUB_PAT}
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${DOCUMENTATION_PATH}:/var/builds/docs
      - ${INSTALLERS_PATH}:/var/builds/installers
    networks:
      - apsim
  db:
    image: mariadb:10
    container_name: builds-db
    restart: unless-stopped
    volumes:
      - /data/builds/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - apsim

networks:
  apsim:
    external: true
