#!/usr/bin/env bash

set -euo pipefail

# Get directory of script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Rebuild docker image.
docker build -f "$DIR/Dockerfile" -t httpd:apsim "$DIR"

# Restart the container with the rebuild image, ignoring any errors while
# stopping the running container.
docker-compose -f "$DIR/docker-compose.yml" down || echo Ignoring errors...
docker-compose -f "$DIR/docker-compose.yml" up -d
