version: '3.1'

services:
  httpd:
    image: httpd:apsim
    container_name: httpd
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - APACHE_LOG_DIR=/usr/local/apache2/logs
    networks:
      - registration_httpd
      - jenkins_httpd
      - builds_httpd
      - vault_httpd
networks:
  registration_httpd:
    external: true
  jenkins_httpd:
    external: true
  builds_httpd:
    external: true
  vault_httpd:
    external: true
